### ISSUE TITLE
Optimize User Data Retrieval in Authentication Middleware

### ISSUE THREAD

**Issue by mohitisimmortal** [last-developer/ether-watches#2]
## Description 
Currently, the authenticateToken middleware only retrieves the username and role from the decoded token, then finds the user in the database and attaches limited data to req.user. In routes like getUserProfile, we end up making a redundant database query to fetch the full user profile.

## To improve efficiency and reduce redundant calls, we should:
- Modify authenticateToken to retrieve the full user profile from the database.
- Attach the complete user data to req.user, eliminating the need for additional database queries in routes like getUserProfile.

## Files to Modify
authenticateToken Middleware **(backend/middlewares/authenticateToken.js)**
getUserProfile Route Handler **(backend/controllers/userController.js)** -exports.getUserProfile...

**Comment by syamjir** [comment]
Hi@mohitisimmortal, Assign me

**Comment by mohitisimmortal** [comment]
will see prs today and close the best one, sorry for delay guys
